### ISSUE TITLE
Concourse bosh credhub release file limits

### ISSUE THREAD

**Issue by blyles** [pivotal/credhub-release#70]
What version of the credhub server you are using?

2.11.2 (Bosh release)

What version of the credhub cli you are using?

2.9.3

If you were attempting to accomplish a task, what was it you were attempting to do?

Concourse interpolate a credhub value

What did you expect to happen?

For it to work.

What was the actual behavior?

2022-07-04T09:33:01.283Z [https-jsse-nio-8844-Acceptor] .... ERROR --- Acceptor: Socket accept failed
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_322]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:421) ~[?:1.8.0_322]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:249) ~[?:1.8.0_322]
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:469) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:71) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:95) [tomcat-embed-core-9.0.34.jar!/:9.0.34]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]

Please confirm where necessary:
* [ ] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by hsinn0** [comment]
@blyles Can you provide more details on the repro steps?

**Comment by Tallicia** [comment]
@blyles Can you provide steps to reproduce or should this be closed?

**Comment by peterhaochen47** [comment]
Closing this issue due to inactivity, please open a new issue if issue persists / more info can be provided.
