### ISSUE TITLE
SSL error on Jammy 1.49 stemcell

### ISSUE THREAD

**Issue by jochenehret** [pivotal/credhub-release#74]
What version of the credhub server you are using?

credhub-release 2.12.14 / cf-deployment v23.2.0
GCP Jammy stemcell:
bosh-google-kvm-ubuntu-jammy-go_agent  1.49*    ubuntu-jammy  -    https://www.googleapis.com/compute/v1/projects/cloud-foundry-310819/global/images/stemcell-1-49-google-kvm-ubuntu-jammy-1668679429

What version of the credhub cli you are using?

N/A

If you were attempting to accomplish a task, what was it you were attempting to do?

Deploy cf-deployment v23.2.0 on Jammy 1.49 with Postgres enabled and TLS disabled:
```
  jobs:
  - name: credhub
    properties:
      credhub:
        data_storage:
          database: credhub
          host: sql-db.service.cf.internal
          password: ((credhub_database_password))
          port: 5524
          require_tls: false
          type: postgres
          username: credhub
```

What did you expect to happen?

Deployment should succeed.

What was the actual behavior?

Starting of job "credhub" failed. The "credhub.log" file showed this exception:
```
Caused by: org.postgresql.util.PSQLException: SSL error: Received fatal alert: handshake_failure
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:43) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:584) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:168) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.Driver.makeConnection(Driver.java:434) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.Driver.connect(Driver.java:291) ~[postgresql-42.5.0.jar!/:42.5.0]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar!/:?]
        at org.cloudfoundry.credhub.config.FlywayMigrationStrategyConfiguration.getConnection(FlywayMigrationStrategyConfiguration.java:46) ~[classes!/:?]
        at org.cloudfoundry.credhub.config.FlywayMigrationStrategyConfiguration.renameMigrationTableIfNeeded(FlywayMigrationStrategyConfiguration.java:32) ~[classes!/:?]
        at org.cloudfoundry.credhub.config.FlywayMigrationStrategyConfiguration.lambda$repairBeforeMigration$0(FlywayMigrationStrategyConfiguration.java:24) ~[classes!/:?]
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:62) ~[spring-boot-autoconfigure-2.7.5.jar!/:2.7.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.23.jar!/:5.3.23]
        ... 26 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:1.8.0_352]
        at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:1.8.0_352]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:311) ~[?:1.8.0_352]
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:1.8.0_352]
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185) ~[?:1.8.0_352]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152) ~[?:1.8.0_352]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397) ~[?:1.8.0_352]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305) ~[?:1.8.0_352]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440) ~[?:1.8.0_352]
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:584) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:168) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.Driver.makeConnection(Driver.java:434) ~[postgresql-42.5.0.jar!/:42.5.0]
        at org.postgresql.Driver.connect(Driver.java:291) ~[postgresql-42.5.0.jar!/:42.5.0]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar!/:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar!/:?]
        at org.cloudfoundry.credhub.config.FlywayMigrationStrategyConfiguration.getConnection(FlywayMigrationStrategyConfiguration.java:46) ~[classes!/:?]
        at org.cloudfoundry.credhub.config.FlywayMigrationStrategyConfiguration.renameMigrationTableIfNeeded(FlywayMigrationStrategyConfiguration.java:32) ~[classes!/:?]
        at org.cloudfoundry.credhub.config.FlywayMigrationStrategyConfiguration.lambda$repairBeforeMigration$0(FlywayMigrationStrategyConfiguration.java:24) ~[classes!/:?]
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:62) ~[spring-boot-autoconfigure-2.7.5.jar!/:2.7.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.23.jar!/:5.3.23]
```

Adding `sslmode=disable` to the database connection URL seems to resolve the issue. Default is `prefer`, but this doesn't seem to work on Jammy 1.49. It worked on Jammy 1.44. Probably one of the many CVE fixes in 1.49 changed the SSL behavior:
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/ubuntu-jammy%2Fv1.49

Could be fixed here: https://github.com/pivotal/credhub-release/blob/5c095554cdf2976b03137f1dd141f8b524aa3b86/jobs/credhub/templates/application_spring.yml.erb#L73
See also https://www.postgresql.org/docs/11/libpq-ssl.html

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by jochenehret** [comment]
If you need help analysing this issue, please contact me. This is currently blocking the cf-deployment release pipeline:
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/fresh-deploy/builds/117

**Comment by dueckminor** [comment]
The Java update (which is part of 2.12.14) changes the TLS handshake a little bit.
CredHub now supports the `TLS_AES_256_GCM_SHA384` and `TLS_AES_128_GCM_SHA256` cipher suites, which the postgres server happily accepts. With the previous version (2.12.13) the server chooses `TLS_RSA_WITH_AES_128_GCM_SHA256`.

The new cipher suites requires that client and server both support the same EC group. Unfortunately some postgres servers out there support only `secp256r1` while CredHub supports only `secp384r1`.

Unfortunately this is not configurable:
https://github.com/pivotal/credhub-release/blob/e2cf9f7fec47c7214bf1b1462f60d1f0725e9e5f/jobs/credhub/templates/ctl.erb#L45 

By removing `-Djdk.tls.namedGroups=\"secp384r1\"` (or replacing it with `-Djdk.tls.namedGroups=\"secp384r1,secp256r1\"`) the affected servers accept the handshake.

**Comment by peterhaochen47** [comment]
While we are still formulating a fix to this issue, we have reverted the underlying change that caused the issue (Java version bump) and released a new patch: [credhub-release v2.12.16](https://github.com/pivotal/credhub-release/releases/tag/2.12.16) which should not have this postgres TLS error. We will bring back the Java bump alongside with a fix to this issue. 

Let's still keep this issue open.

**Comment by rkoster** [comment]
Is the issue still blocking the integration of the credhub-release into cf-deployment?

**Comment by jochenehret** [comment]
No, the latest version 2.12.18 has been successfully integrated into cf-deployment:
https://github.com/cloudfoundry/cf-deployment/releases/tag/v24.3.0

**Comment by peterhaochen47** [comment]
> Is this issue still blocking the integration of the credhub-release into cf-deployment?

The latest credhub-release has no integration issue with cf-deployment. This issue is only blocking credhub-release from getting a new Java 8 bump (because if this issue persists, the credhub-release with a new Java 8 will have compatibility issue with cf-deployment due to some postgres issue).

The team is attempting to bump directly to Java 11 currently, so we will evaluate this issue after that.

**Comment by peterhaochen47** [comment]
This issue should be fixed by commit https://github.com/pivotal/credhub-release/commit/b6a6fac08372abc770864785619e2335d914677d. Closing this issue, but please reopen if this issue persists.

**Comment by peterhaochen47** [comment]
This is the release containing the fix: https://github.com/pivotal/credhub-release/releases/tag/2.12.27
Let us know if it doesn't work.
